# Generated by Django 4.2.5 on 2024-06-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('reg_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('batch', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('cgpa', models.FloatField()),
                ('sslc', models.FloatField()),
                ('hsc', models.FloatField()),
                ('bag_of_log', models.TextField(blank=True, null=True)),
                ('no_of_arrear', models.IntegerField()),
                ('semester1', models.FloatField(blank=True, null=True)),
                ('semester2', models.FloatField(blank=True, null=True)),
                ('semester3', models.FloatField(blank=True, null=True)),
                ('semester4', models.FloatField(blank=True, null=True)),
                ('semester5', models.FloatField(blank=True, null=True)),
                ('semester6', models.FloatField(blank=True, null=True)),
                ('semester7', models.FloatField(blank=True, null=True)),
                ('semester8', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
