# Generated by Django 4.2.5 on 2024-06-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_student_semester1_alter_student_semester2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('conform_Password', models.CharField(max_length=100)),
            ],
        ),
    ]
