# Generated by Django 5.0.7 on 2024-07-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0004_user_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="no_of_arrear",
            new_name="history_of_arrear",
        ),
    ]
