# Generated by Django 5.0.7 on 2024-07-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0004_user_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="no_of_arrear",
            new_name="history_of_arrear",
        ),
        migrations.AddField(
            model_name="student",
            name="diploma",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="bag_of_log",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="hsc",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
