# Generated by Django 5.0.7 on 2024-07-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0005_rename_no_of_arrear_student_history_of_arrear_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="diploma",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="hsc",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
