# Generated by Django 5.0.7 on 2024-07-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0006_alter_student_diploma_alter_student_hsc"),
    ]

    operations = [
        migrations.CreateModel(
            name="defalut_email_id",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_id", models.CharField(max_length=100)),
            ],
        ),
    ]
