# Generated by Django 5.0.6 on 2024-08-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_defalut_email_id_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
